# crawler_config.yml

# Name of news website that want to crawls (vnexpress, vietnamnet)
webname: "vietnamnet"

# tasks = ["url", "type"]
task: "url"

#logger config file path
logger_fpath: "logger/logger_config.yml"
urls_fpath: "urls.txt"
output_dpath: "result"
num_workers: 4

# if task == "type": 
# article_type == "all" to crawl all of types
article_type: "du-lich"
total_pages: 1